paths:
    default: <absolute path>
    L0: null
    L1A: null
    L1B: null
    L2: null
    output: null
    external: null
    logs: null

station:
    latitude: 51.9989
    longitude: 4.3733585
    altitude: 95

space-track.org:
    user: <USERNAME>
    password: <PASSWORD>

runtime:
    logging: false