paths:
    default: null
    L0: null
    L1A: null
    L1B: null
    L1C: null
    output: null
    external: null
    logs: null
    analysis: null

station:
    latitude: 51.9989
    longitude: 4.3733585
    altitude: 95

credentials:
    space-track.org:
        user: <USERNAME>
        password: <PASSWORD>

runtime:
    logging: false