function [output] = readPrediction(infile)
%
% This function loads the text file generated by get5dayPrediction
%
% Bart Root, 17 May 2015
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% loading the file
M = load(infile);

% generate structure
output = struct();

output.init = M(1,:);
output.prediction = M(2:end,:);
