#!/bin/bash
#
# get TLE from Space-track.org websit

NORADID=$1

if [ -s $NORADID ]; then
	# default value: Delfi-C3
	NORADID=32789
fi
	
echo $NORADID

curl -c cookies.txt -b cookies.txt -k https://www.space-track.org/ajaxauth/login -d "identity=bart_root&password=delfi-c3delfi-c3&query=https://www.space-track.org/basicspacedata/query/class/tle_latest/ORDINAL/1/NORAD_CAT_ID/${NORADID}/orderby/TLE_LINE1%20ASC/format/tle" > temp_TLE.txt

# check if a new TLE is made, if so replace the old one.
if [ -s temp_TLE.txt ]
then
	rm TLE_${NORADID}.txt
	mv temp_TLE.txt TLE_${NORADID}.txt
else 	
	touch TLE_isempty.txt
	rm temp_TLE.txt	
fi

